package com.example.convo_z.utils;

public enum Constants {
    CASE_GOOGLE_OR_EMAIL_SIGNUP,
    CASE_PHONE_SIGNUP,
    CASE_PROFILE_UP_TO_DATE,
    CASE_ACCOUNT_LINKING,
    CASE_SIGN_IN_OR_SIGN_UP,
    CASE_NEW_USER,
    CASE_OLD_USER,
    CASE_DISABLE_HOME,
    CASE_DO_NOT_DISABLE_HOME,
    CASE_STATUS_FRAGMENT,
    CASE_OWN_STATUS_PAGE,
    CASE_HOME_ACTIVITY,
}
